<a href="https://colab.research.google.com/github/jpcompartir/dl_notebooks/blob/main/tf_recap_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
x = tf.ones(shape = (2, 1)) #equivalent to np.ones
x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>

In [5]:
x = tf.random.uniform(shape = (3, 1), minval = 0., maxval = 1.) #equivalent to np.random.unfirm
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.52495754],
       [0.20644116],
       [0.00975478]], dtype=float32)>

The first signifanct difference between TF Tensors and Numpy arrays is that TF tensors are not assignable - they are constants. So we cannot assign a tf.tensor to a variable, like we can a np.array!

Instead, we need a tf.Variable() object (which we saw in our NN implementation). We can then track the variable's state and make changes to it (in this case, the weights tensor, recall the weights tensor is where our model's knowledge is stored). 

*Changes are made to TF Variables by their .assign() method.*

In [7]:
 v = tf.Variable(initial_value = tf.random.normal(shape = (3, 1)))
 v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 0.15181033],
       [-1.7959397 ],
       [-0.9345837 ]], dtype=float32)>

In [9]:
v.assign(tf.ones((3, 1))) #We place the tuple(3, 1) to the tf.ones() call inside the assign() call
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

We can also slice the tensor and assign separately:

In [10]:
v[0, 0].assign(3.)
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[3.],
       [1.],
       [1.]], dtype=float32)>

We can use assign_add() and assign_sub() to mimic the behaviour of += and -= respectively.

There are also a number of tensor operations we can call on a TF Tensor:

In [13]:
a = tf.ones(
    (2, 2)
)
b = tf.square(a)
c = tf.sqrt(a)
d = b + c
e = tf.matmul(a, b)
e *= d
a, b, c, d, e

(<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[1., 1.],
        [1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[2., 2.],
        [2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
 array([[4., 4.],
        [4., 4.]], dtype=float32)>)

Moving into the GradientTape API - one of the key upgrades from Numpy to Tf. GradientTape() allows us to retrieve the gradient of any differentiable equation! Incredibly important for training neural networks!